version: '3.5'
services:

  moodle:
    build: .
    ports:
      - "80:80"
    volumes:
      - "./moodle:/var/www/moodle"
      - "./moodledata:/var/www/moodledata"
    networks:
      - eadnet
    container_name: moodle

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "q1w2e3"
      MYSQL_DATABASE: "moodle"
      MYSQL_USER: "moodleuser"
      MYSQL_PASSWORD: "q1w2e3"
    ports:
      - "3306:3306"
    volumes:
      - "./banco:/var/lib/mysql"
    networks:
      - eadnet
    container_name: mysql

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - eadnet
    container_name: redis

networks:
  eadnet:
    driver: bridge  
