version: '3.7'
services:

  moodle:
    image: moodlel
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: moodledata
        target: /var/www/moodledata
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "q1w2e3"
      MYSQL_DATABASE: "moodle"
      MYSQL_USER: "moodleuser"
      MYSQL_PASSWORD: "q1w2e3"
    ports:
      - "3306:3306"
    volumes:
      - "banco:/var/lib/mysql"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
          
  redis:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 256M
networks:
  eadnet:
    driver: bridge  
volumes:
  banco:
  moodledata:
    driver_opts:
      type: "nfs"
      o: "addr=200.100.50.101,nolock,soft,rw"
      device: ":/home/suporte/storage/moodledata"
