version: '2.4'
services:

  moodle:
    build: .
    ports:
      - "80:80"
    volumes:
      - "./moodledata:/var/www/moodledata"
    networks:
      - eadnet
    container_name: moodle
    mem_limit: 2048m
    cpu_count: 3
    cpu_percent: 50

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "q1w2e3"
      MYSQL_DATABASE: "moodle"
      MYSQL_USER: "moodleuser"
      MYSQL_PASSWORD: "q1w2e3"
    ports:
      - "3306:3306"
    volumes:
      - "./banco:/var/lib/mysql"
    networks:
      - eadnet
    container_name: mysql
    mem_limit: 1024m
    cpu_count: 2
    cpu_percent: 50
          
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - eadnet
    container_name: redis
    mem_limit: 1024m
    cpu_count: 2
    cpu_percent: 50

networks:
  eadnet:
    driver: bridge  
