version: '3.7'
services:

  moodle:
    build: .
    ports:
      - "80:80"
    volumes:
      - "./moodledata:/var/www/moodledata"
    networks:
      - eadnet
    container_name: moodle
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "q1w2e3"
      MYSQL_DATABASE: "moodle"
      MYSQL_USER: "moodleuser"
      MYSQL_PASSWORD: "q1w2e3"
    ports:
      - "3306:3306"
    volumes:
      - "./banco:/var/lib/mysql"
    networks:
      - eadnet
    container_name: mysql
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
          
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - eadnet
    container_name: redis
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 256M
networks:
  eadnet:
    driver: bridge  

#Adicionar NFS
